# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AAA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True)),
                ('path', models.FilePathField(editable=False)),
                ('fitting_date', models.DateField()),
                ('uploaded_date', models.DateTimeField(blank=True)),
                ('download_count', models.IntegerField(blank=True, default=0)),
                ('notes', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FittingRecord', to='AAA.user_ext')),
            ],
        ),
    ]
