# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-08-06 07:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_ext',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='date bithed')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='phone number')),
                ('is_male', models.BooleanField(default=False, verbose_name='gender')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='province')),
                ('state', models.CharField(blank=True, max_length=30, verbose_name='state')),
                ('street', models.CharField(blank=True, max_length=128, verbose_name='street')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
