# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=40, unique=True)),
                ('verify', models.CharField(max_length=20)),
                ('passcode', models.CharField(blank=True, max_length=10)),
                ('valid_expires', models.DateTimeField(blank=True, null=True)),
                ('locked_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user_ext',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='phone number'),
        ),
    ]
